#!/usr/bin/env bash
# Transfers a file from our client to a server.
# Accepts four arguments:
#+    The path to the file to be transferred/ name of the file.($1)
#+    The IP of the server to transfer the file to.($2)
#+    The username that scp connects with/ username of the server.($3)
#+    The path to the SSH private key that scp uses/ private key on loacl machine.($4)

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  #Transfer the file using scp with the given arguments.
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
